### ISSUE TITLE
Link to policy reference is wrong

### ISSUE THREAD

**Issue by ronanquillevere** [ExpressGateway/express-gateway.io#105]
Inside the following section
http://www.express-gateway.io/docs/configuration/gateway.config.yml/policies

_"For all policies supported by Express Gateway please see the Policy Reference"_

The link for the Policy Reference provided is wrong : http://www.express-gateway.io/docs/configuration/gateway.config.yml/Policy%20Reference

From what I understand, it should be : http://www.express-gateway.io/docs/policies/

**Comment by altsang** [comment]
many, many thx @ronanquillevere!
