### ISSUE TITLE
Simpler Logger policy description

### ISSUE THREAD

**Issue by ronanquillevere** [ExpressGateway/express-gateway.io#106]
Inside the following page : http://www.express-gateway.io/docs/policies/simple-logger

1) The description of the simpler logger policy seems wrong to me.

_The Simpler Logger policy provides capability for logging with basic message output. the JavaScript [ES6 template literal syntax][es6-template-literal-syntax]_

2) Inside the option reference the link to "ES6 template literal syntax" is rendered over "Javascript" for me on linux with Chrome 60.0.3112.113, maybe a missing space ?

**Comment by altsang** [comment]
many, many thx @ronanquillevere !
