### ISSUE TITLE
User experience - Enable search for the website

### ISSUE THREAD

**Issue by XVincentX** [ExpressGateway/express-gateway.io#119]
I've been struggling multiple times searching for concepts and documents around the website. A search implementation is mandatory and [Algolia](https://algolia.com) can really be helpful.

They even have a free plan that should suit us perfectly.

**Comment by altsang** [comment]
have registered for Algolia, filled out the OSS qualification form. Waiting for qualification and approval. We'll need search UX and VD integrated into the current website.

**Comment by altsang** [comment]
mocks for search interface:


search active:
![Mockup_Search_active.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ffa3cb7ac4e6020067d614/125516c66e82c728ace21e0d46c59b9928979396bcecbe51a755cf952a522e652c46ef696097ec22ba416f43554d4ba5435c0a46fff9dd2ff4b46d268a5c5aebd0680e7d926e03b0aac04ee155e57dd205d0f4ae805ec1ee3724e28b8949381f001e89f85531b2d4.jpg)

search at rest:
![Mockup_Search_at-rest.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ffa3cb7ac4e6020067d614/125516c66e82c728ace21e0d46c59b9928979396bcecbe51a755cf953d0b35763a10e1673295f127b54778154d555ca9485a5b11fefa897fa2e43e21dc5c0bbcd76c5a25cf6942bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8f493818041d8fff5a33a38b06.jpg)

search rollover:
![Mockup_Search_Rollover.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ffa3cb7ac4e6020067d614/125516c66e82c728ace21e0d46c59b9928979396bcecbe51a755cfa6264a2b7c3f01b1693cc7f33ab0487e021b4d44be44515d40a9fb8a2bf2b26e72db0a0bed806b5e71973445ffaa9e0dfd50e474d412dcfce9c85ecafa3c22ed8a8a4f381803198cf95d32a79a5985.jpg)

**Comment by altsang** [comment]
@XVincentX you think you can take something like this on?

**Comment by XVincentX** [comment]
Sure thing sir - I'll work on it.

**Comment by XVincentX** [comment]
@altsang Let's discuss the alternatives in Slack.
