### ISSUE TITLE
Admin: spec for API signatures for new API

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway.io#142]
- extend your current OpenAPI spec - adding to what we already have
- examples of fine grain and course grain manipulation
- examples of URL structures
- overall architecture to do client interaction - CLI + web GUI (including JSON schema based validation and typing etc)

**Comment by DrMegavolt** [comment]
https://docs.google.com/document/d/1qgeYckdTuoQE24wZrju40jef92nTeNO0nIQXyfsCA38/edit#

**Comment by DrMegavolt** [comment]
duplicate  of #387
