### ISSUE TITLE
List of Must have Doc updates for upcoming  1.4

### ISSUE THREAD

**Issue by DrMegavolt** [ExpressGateway/express-gateway.io#170]
- [ ] Advanced policy with access to pluginContext
- [ ] API endpoint for service\api -endpoints, policies, schema etc. 
- [ ] EG behind proxy 
- [x] EG with redis Sentinels 
- [x] Multi-Auth
- [x] App name alias support
- [ ] Importing data and building test data set
   + [x] Update CLI example to show how to set keyId keySecret when creating  
- [x] Redis Migration 

[Update with whatever is missing]

**Comment by XVincentX** [comment]
@DrMegavolt 
Could you clarify what do the following point mean?

- Advanced policy with access to pluginContext
- API endpoint for service\api -endpoints, policies, schema etc. 
- EG behind proxy

**Comment by DrMegavolt** [comment]
- Advanced policy is example plugin. will be document once ready to merge
- EG behind proxy I've not committed, basically how to be when you have forward corporate proxy 

- API endpoint for service\api -endpoints, policies, schema etc. 
same way as we have Admin API docs for users\apps etc
