### ISSUE TITLE
EG: fix CSS for blog post styling

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway.io#197]

**Comment by XVincentX** [comment]
URLS do not get spaces with the surrounding text:
![image](https://user-images.githubusercontent.com/1416224/35738873-54ee708e-0830-11e8-81a5-06be2b9627c8.png)

**Comment by XVincentX** [comment]
Also when you click into a blog post... the anchor links are underlined and they should not be, they should just be blue text

**Comment by XVincentX** [comment]
On hold until @altsang clarifies what we want to do with the underline links.
