### ISSUE TITLE
How to config https

### ISSUE THREAD

**Issue by RayLLiu** [ExpressGateway/express-gateway.io#205]
I am using GoDaddy for SSL certification and i got two `.crt` files.

I also generated `.csr`file. And I put all combinations for key and cert but still not working.

`https:
  port: 443
  tls:
    "*.example.com":
        key: example.com.csr
        cert: 7e5f2a7e8fa0962d.crt`

I got 

`_tls_common.js:104
      c.context.setKey(options.key, options.passphrase);
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.createSecureContext (_tls_common.js:104:17)
    at TLSSocket.options.SNICallback [as _SNICallback] (/root/BubbleHRWebAppGateway/node_modules/express-gateway/lib/gateway/server.js:60:24)
    at loadSNI (_tls_wrap.js:113:8)
    at TLSSocket.oncertcb (_tls_wrap.js:193:3)
    at TLSWrap.ssl.oncertcb (_tls_wrap.js:452:39)`

Can EG provide more detailed documentation for https configuration?

Thank you so much!

**Comment by XVincentX** [comment]
Hey — thanks a lot for the issue. We can definitely work this out somehow.

I went through the docs and it seems to be clear enough to me.

According to the section you quoted in the issue, I can see that as `key` you're providing a `.csr` file, that's a `Certificate Signin Request` file; it's not what you need to put there, definitely.

If you can provide more details — I could help you out. Try to jump to our Gitter channel to get real time responses!
