### ISSUE TITLE
GDPR: eg.io needs to be compliant on email submission

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway.io#244]

**Comment by XVincentX** [comment]
**Note:** I fixed this on the fly while speaking with Dellaena earlier this morning.

**Comment by XVincentX** [comment]
![image](https://user-images.githubusercontent.com/1416224/40672508-51d6ea58-636f-11e8-9256-5a6d61428796.png)
![image](https://user-images.githubusercontent.com/1416224/40672513-56508738-636f-11e8-9c11-38ad893709a9.png)
