### ISSUE TITLE
expressions plugin is missing on Plugins page

### ISSUE THREAD

**Issue by altsang** [ExpressGateway/express-gateway.io#262]
need to add icon for expressions plugin
- need new icon from VD
- need to make room under utilities section

**Comment by XVincentX** [comment]
@altsang Just a clarification: Expression is not a plugin, is built in in Express Gateway.

**Comment by altsang** [comment]
understood, they were all suppose to be plugins at once point, some were going to be core, right now `expression` is a core policy correct? it needs an icon either way

**Comment by XVincentX** [comment]
Expression is now in the core, correct.

> Were all suppose to be plugins at once point

Yes. This is not possible yet unfortunately, our plugin system does not allow database operations and some policies are touching EG's internals we can't expose at this point.

**Comment by XVincentX** [comment]
@altsang Do we have the icon in place?

**Comment by altsang** [comment]
we do not, waiting for designers to be onboarded so we can start that conversation
