### ISSUE TITLE
Small bug in docs: comma in yml example - policies/headers

### ISSUE THREAD

**Issue by ingo-eichhorst** [ExpressGateway/express-gateway.io#265]
On the page: [docs/policies/headers/](https://www.express-gateway.io/docs/policies/headers/) is a typo.

```yml
              headersPrefix: 'eg-',
```

should be (removed comma after 'eg-')
```yml
              headersPrefix: 'eg-'
```

**Comment by XVincentX** [comment]
@ingo-eichhorst Thanks for the note! Are you willing to open a PR for that? :)

**Comment by ingo-eichhorst** [comment]
@XVincentX The PR is ready but it looks like I have no permissions to open a PR in Github.


```bash
git push origin fix/typo_in_policies_headers
remote: Permission to ExpressGateway/express-gateway.io.git denied to ingo-eichhorst
```

Can you grant me access? Thanks.

**Comment by XVincentX** [comment]
@ingo-eichhorst You need to fork the repo on your local account — then you'll be able to open a PR against this repo.

**Comment by ingo-eichhorst** [comment]
@XVincentX Perfect. Worked like a charm.
Can you please review the small changed. I've build and checked the pages with jekyll on my lokal machine.

**Comment by XVincentX** [comment]
Merged!
