### ISSUE TITLE
RSS feed for a blog

### ISSUE THREAD

**Issue by medikoo** [ExpressGateway/express-gateway.io#90]
It'll be great to have it, so we can track new publications.

As a side note, in  head `/atom.xml` link is listed, but it resolves to 404

**Comment by altsang** [comment]
thx for the feedback medikoo, I'll take this up with @brandonbrown and see what's possible, we're still fixing up the blog with basic stuff like excerpts which is coming up

**Comment by altsang** [comment]
@medikoo - we're on GitHub pages and they only support a certain number of sanctioned plugins. The one that we can use is Jekyll-feed and there's already an Atom Feed - http://express-gateway.io/feed.xml instead of /atom.xml

**Comment by medikoo** [comment]
@altsang Thanks, I see it works.
It'll be probably good if you make that RSS discoverable. Currently there's no way to find it, and reference head points 404 link.
